import { roles, defaults, builtinPresets, rgb, fromRgb, toHsv, fromHsv, normalizeHex, validatePalette, clamp } from './model.js';
import { screens, renderScreen, loadMap, makeMap } from './screens.js';
const $ = id => document.getElementById(id);
const STORAGE = 'journeydeck-theme-creator-v1';
let palette={...defaults}, presets=[], selected='base', hsv=toHsv(palette.base), originals=false, pending=false, map='', lastMapKey='';
const notice=message=>$('notice').textContent=message;
try { const stored=JSON.parse(localStorage.getItem(STORAGE)||'null'); if(stored){palette=validatePalette(stored.palette);presets=(Array.isArray(stored.presets)?stored.presets:[]).slice(0,100).flatMap(p=>{try{return [{id:String(p.id),name:String(p.name).slice(0,60),palette:validatePalette(p.palette)}];}catch{return [];}});}}catch{notice('Saved browser data could not be read. The original palette is loaded.');}
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify({palette,presets}));}catch{notice('Browser storage is unavailable or full. Export your palette to keep it.');return false;}return true;}
function swatches(values){const el=document.createElement('span');el.className='mini-swatches';['base','card','text','accent','active'].forEach(k=>{const sw=document.createElement('i');sw.style.background=values[k];el.append(sw);});return el;}
builtinPresets.forEach(p=>{
 const button=document.createElement('button'),name=document.createElement('span');
 button.className='builtin-preset';button.dataset.theme=p.id;button.title=`Apply ${p.name}`;
 name.textContent=p.name;button.append(name,swatches(p.palette));
 button.addEventListener('click',()=>{
  palette={...p.palette};
  if(originals){originals=false;$('compare').setAttribute('aria-pressed','false');$('compare').textContent='View originals';}
  syncPicker();schedule();persist();notice(`Applied “${p.name}”. Edit any color and save your own variation.`);
 });
 $('builtin-list').append(button);
});
roles.forEach(([key,label,,description],i)=>{const button=document.createElement('button');button.className='role';button.dataset.role=key;button.setAttribute('aria-label',label);const sw=document.createElement('span');sw.className='swatch';const name=document.createElement('span');name.textContent=label;const value=document.createElement('span');value.className='value';button.append(sw,name,value);button.addEventListener('click',()=>{selected=key;syncPicker();});$('categories').append(button);});
const dl=document.createElement('dl');roles.forEach(([,label,,description])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=description;dl.append(dt,dd);});$('mapping').append(dl);
screens.forEach(([id,label,number])=>{const article=document.createElement('article');article.className='screen-card';article.innerHTML=`<div class="screen-label">${label}<span>${number} / LIVE PREVIEW</span></div><div class="screen-frame" id="preview-${id}"></div>`;$('screens').append(article);});
function syncPicker(keepHsv=false){document.querySelectorAll('.builtin-preset').forEach(button=>{const preset=builtinPresets.find(p=>p.id===button.dataset.theme);button.setAttribute('aria-pressed',String(roles.every(([key])=>palette[key]===preset.palette[key])));});if(!keepHsv)hsv=toHsv(palette[selected]);const role=roles.find(([k])=>k===selected);$('picker-title').textContent=role[1];$('role-description').textContent=role[3];$('hex').value=palette[selected].toUpperCase();$('hex').setCustomValidity('');rgb(palette[selected]).forEach((v,i)=>$( ['r','g','b'][i]).value=v);$('current-chip').style.background=palette[selected];$('sv').style.background=`linear-gradient(to top,#000,transparent),linear-gradient(to right,#fff,transparent),hsl(${hsv[0]} 100% 50%)`;$('sv-handle').style.left=`${hsv[1]*100}%`;$('sv-handle').style.top=`${(1-hsv[2])*100}%`;$('sv').setAttribute('aria-valuenow',Math.round(hsv[1]*100));$('sv').setAttribute('aria-valuetext',`Saturation ${Math.round(hsv[1]*100)}%, brightness ${Math.round(hsv[2]*100)}%`);$('hue').value=hsv[0];document.querySelectorAll('.role').forEach(button=>{const k=button.dataset.role;button.classList.toggle('selected',selected===k);button.setAttribute('aria-pressed',String(selected===k));button.querySelector('.swatch').style.background=palette[k];button.querySelector('.value').textContent=palette[k].toUpperCase();});}
function render(){pending=false;const key=['base','raised','text','muted','accent'].map(k=>palette[k]).join('');if(key!==lastMapKey){map=makeMap(palette);lastMapKey=key;}screens.forEach(([id,label])=>{$('preview-'+id).innerHTML=originals?`<img src="assets/${id}.png" alt="Original ${label} screenshot">`:renderScreen(id,palette,map);});document.querySelectorAll('.screen-label span').forEach((el,i)=>el.textContent=`0${i+1} / ${originals?'ORIGINAL':'LIVE PREVIEW'}`);}
function schedule(){if(!pending){pending=true;requestAnimationFrame(render);}}
function update(value,keepHsv=false){palette[selected]=value;syncPicker(keepHsv);schedule();persist();}
function movePicker(e){const b=$('sv').getBoundingClientRect();hsv[1]=clamp((e.clientX-b.left)/b.width,0,1);hsv[2]=1-clamp((e.clientY-b.top)/b.height,0,1);update(fromHsv(...hsv),true);}
$('sv').addEventListener('pointerdown',e=>{if(e.button!==0)return;$('sv').setPointerCapture(e.pointerId);movePicker(e);});
$('sv').addEventListener('pointermove',e=>{if($('sv').hasPointerCapture(e.pointerId))movePicker(e);});
$('sv').addEventListener('keydown',e=>{const step=e.shiftKey?.1:.01;if(e.key==='ArrowRight')hsv[1]+=step;else if(e.key==='ArrowLeft')hsv[1]-=step;else if(e.key==='ArrowUp')hsv[2]+=step;else if(e.key==='ArrowDown')hsv[2]-=step;else return;e.preventDefault();hsv[1]=clamp(hsv[1],0,1);hsv[2]=clamp(hsv[2],0,1);update(fromHsv(...hsv),true);});
$('hue').addEventListener('input',()=>{hsv[0]=Number($('hue').value);update(fromHsv(...hsv),true);});
$('hex').addEventListener('input',()=>{const v=normalizeHex($('hex').value);$('hex').setCustomValidity(v?'':'Enter a 3- or 6-digit HEX color.');if(v&&$('hex').value.replace('#','').length===6)update(v);});
$('hex').addEventListener('change',()=>{const v=normalizeHex($('hex').value);if(v)update(v);else{$('hex').reportValidity();}});
['r','g','b'].forEach(id=>$(id).addEventListener('input',()=>{const values=['r','g','b'].map(k=>$(k).value);if(values.every(v=>v!==''&&Number.isFinite(Number(v))&&Number(v)>=0&&Number(v)<=255))update(fromRgb(values.map(Number)));}));
function renderPresets(){$('preset-list').replaceChildren();if(!presets.length){const empty=document.createElement('p');empty.className='footnote';empty.textContent='Your saved palettes will appear here.';$('preset-list').append(empty);}presets.forEach(p=>{const row=document.createElement('div');row.className='preset-row';const load=document.createElement('button'),name=document.createElement('span');name.className='preset-label';name.textContent=p.name;load.title=`Apply ${p.name}`;load.append(name,swatches(p.palette));load.addEventListener('click',()=>{palette={...p.palette};syncPicker();schedule();persist();notice(`Applied “${p.name}”.`);});const del=document.createElement('button');del.className='delete';del.textContent='×';del.setAttribute('aria-label',`Delete preset ${p.name}`);del.addEventListener('click',()=>{presets=presets.filter(item=>item.id!==p.id);persist();renderPresets();notice(`Deleted “${p.name}”.`);});row.append(load,del);$('preset-list').append(row);});}
$('save-form').addEventListener('submit',e=>{e.preventDefault();const name=$('preset-name').value.trim();if(!name){notice('Enter a name for your preset.');return;}if(presets.length>=100){notice('You have 100 saved presets. Delete a preset before adding another.');return;}let unique=name,n=2;while(presets.some(p=>p.name===unique))unique=`${name} (${n++})`;presets.push({id:crypto.randomUUID(),name:unique,palette:{...palette}});const saved=persist();renderPresets();$('preset-name').value='';if(saved)notice(`Saved “${unique}” in this browser.`);});
$('reset').addEventListener('click',()=>{palette={...defaults};syncPicker();schedule();persist();notice('Original palette restored. Your saved presets are still available.');});
$('compare').addEventListener('click',()=>{originals=!originals;$('compare').setAttribute('aria-pressed',String(originals));$('compare').textContent=originals?'Return to live preview':'View originals';render();});
$('zoom').addEventListener('input',()=>{$('screens').style.setProperty('--preview-width',$('zoom').value+'px');});
$('export').addEventListener('click',()=>{const name=$('preset-name').value.trim()||'JourneyDeck palette';const data={format:'journeydeck-theme-creator',version:1,name,palette,roles:Object.fromEntries(roles.map(([k,label,,description])=>[k,{label,description}]))};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name.replace(/[^a-z0-9_-]/gi,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Palette exported. Save it as a preset here for one-click recall.');});
$('import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error('Palette files must be smaller than 1 MB.');const data=JSON.parse(await file.text());const imported=validatePalette(data.palette);palette=imported;$('preset-name').value=String(data.name||'Imported palette').slice(0,60);syncPicker();schedule();persist();notice('Palette imported. Choose Save to keep a named preset.');}catch(error){notice(`Import failed: ${error.message}`);}finally{e.target.value='';}});
syncPicker();renderPresets();render();
try{await loadMap();lastMapKey='';render();}catch{notice('The journey screenshot could not be loaded. Check the local assets folder.');}

