'use strict';
const $ = id => document.getElementById(id);
const SOURCES = {overture:{name:'Overture',color:'#9169cb',note:'Merged open directory · Includes multiple contributors'},foursquare:{name:'Foursquare',color:'#e87194',note:'Original Open Places dataset · Places Portal'},osm:{name:'OpenStreetMap',color:'#46aa94',note:'Named POIs · Points and mapped area centers'}};
let csrf='',connected=false,runId=0,busy=false,current=null;
let ratings={},selected={},results={},cases=[];
const markerLookup={overture:new Map(),foursquare:new Map(),osm:new Map()};
const matches=p=>{const q=$('filter').value.trim().toLowerCase();return !q||[p.name,p.category,p.address].join(' ').toLowerCase().includes(q);};
$('filter').addEventListener('input',()=>{renderProviders();Object.keys(SOURCES).forEach(renderMarkers);});
try { cases=JSON.parse(localStorage.getItem('jd-places-lab-cases')||'[]'); if(!Array.isArray(cases))cases=[]; } catch { cases=[]; }
const map=L.map('map',{zoomControl:false}).setView([32.75,-97.33],15);
L.control.zoom({position:'topright'}).addTo(map);
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
const layers=Object.fromEntries(Object.keys(SOURCES).map(s=>[s,L.layerGroup().addTo(map)]));
const pin=L.marker([32.75,-97.33],{draggable:true,icon:L.divIcon({className:'stop-marker',iconSize:[20,20],iconAnchor:[10,10]})}).addTo(map);
const circle=L.circle(pin.getLatLng(),{radius:300,color:'#f18c65',fillColor:'#f18c65',fillOpacity:.06,weight:1.5,dashArray:'5 6'}).addTo(map);
function text(tag,value,cls){const n=document.createElement(tag);n.textContent=value;if(cls)n.className=cls;return n;}
function fields(){return {lat:Number($('lat').value),lon:Number($('lon').value),radius:Number($('radius').value)};}
function invalidate(){runId++;current=null;ratings={};selected={};results={};busy=false;$('compare').disabled=false;$('save').disabled=true;Object.values(layers).forEach(l=>l.clearLayers());renderProviders();}
function position(lat,lon,pan=false){if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>80||Math.abs(lon)>179.9)return;invalidate();$('lat').value=lat.toFixed(6);$('lon').value=lon.toFixed(6);pin.setLatLng([lat,lon]);circle.setLatLng([lat,lon]);if(pan)map.setView([lat,lon],16);$('global-status').textContent='Pin updated. Compare to load real nearby places.';}
map.on('click',e=>position(e.latlng.lat,e.latlng.lng));pin.on('dragend',()=>position(pin.getLatLng().lat,pin.getLatLng().lng));
['lat','lon'].forEach(id=>$(id).addEventListener('change',()=>{if(!$('lat').value||!$('lon').value)return;const p=fields();position(p.lat,p.lon,true);}));
$('radius').addEventListener('input',()=>{invalidate();circle.setRadius(Number($('radius').value));$('radius-value').value=$('radius').value+' m';$('map-radius').textContent=$('radius').value+' m search area';});
document.querySelectorAll('[data-layer]').forEach(el=>el.addEventListener('change',()=>{const l=layers[el.dataset.layer];el.checked?l.addTo(map):map.removeLayer(l);}));
async function api(path,body){const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Token':csrf},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw Error(value.error||'Request failed');return value;}
async function status(){const response=await fetch('/api/status');const s=await response.json();csrf=s.csrf;connected=s.foursquare;$('connect').textContent=connected?'Foursquare connected':'Connect Foursquare';}
$('search-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;$('search-results').replaceChildren(text('p','Finding public places…','hint'));try{const r=await api('search',{q:$('search').value.trim()});$('search-results').replaceChildren();if(!r.results.length)$('search-results').append(text('p','No search results. Try a city or enter coordinates.','hint'));r.results.forEach(place=>{const b=text('button',place.name);b.type='button';b.onclick=()=>{position(place.lat,place.lon,true);$('expected').value=place.name.split(',')[0];$('search-results').replaceChildren();};$('search-results').append(b);});}catch(err){$('search-results').replaceChildren(text('p',err.message,'hint'));}finally{button.disabled=false;}});
function renderProviders(){const host=$('providers');host.replaceChildren();for(const [source,config] of Object.entries(SOURCES)){const result=results[source];const panel=text('article','','provider panel');const head=text('div','','provider-header');const row=text('div','','section-row');const name=text('h3',config.name);const dot=text('i','');dot.style.background=config.color;name.prepend(dot);row.append(name,text('span',result?.status==='ok'?'Ready':result?.status==='loading'?'Loading':result?.status==='error'?'Unavailable':source==='foursquare'&&!connected?'Connect':'Open data','badge'));head.append(row,text('p',config.note,'source-note'));head.append(text('p',result?.status==='ok'?`${result.total} places · ${result.seconds}s${result.cached?' · cached':''} · ${result.release}`:'Results appear after you compare a pin.','provider-meta'));panel.append(head);const list=text('div','','result-list');if(result?.status==='ok'&&result.places.length&&!result.places.some(matches))list.append(text('p','No results match this text filter. Clear it to inspect the full list.','empty'));
if(!result||result.status!=='ok'){const message=result?.message||(result?.status==='loading'?'Reading nearby places… First lookup may take a minute.':source==='foursquare'&&!connected?'Connect your Places Portal token to bring this source into the comparison.':'Ready for your first destination.');list.append(text('p',message,'empty'+(result?.status==='loading'?' loading':'')));if(source==='foursquare'&&!connected){const b=text('button','Connect Foursquare','outline');b.onclick=()=> $('connection').showModal();list.append(b);}}
else if(!result.places.length)list.append(text('p','No named places within this radius. Try a wider area, or rate this source as Missing.','empty'));
else result.places.forEach((place,index)=>{if(!matches(place))return;const item=text('div','','result'+(selected[source]===place.id?' selected':''));item.tabIndex=0;item.setAttribute('role','button');item.setAttribute('aria-label',`Inspect ${place.name}, ${Math.round(place.distance)} meters away`);item.append(text('span',String(index+1),'rank'));const detail=text('div','');const title=text('div',place.name,'result-name');title.prepend(text('span',Math.round(place.distance)+' m','distance'));detail.append(title,text('div',place.category||'Category not supplied','result-detail'));if(place.address)detail.append(text('div',place.address,'result-detail'));let extra=[];if(place.confidence!=null)extra.push(`Existence confidence ${Math.round(place.confidence*100)}%`);if(place.status)extra.push(place.status);if(place.geometry)extra.push(place.geometry);if(place.refreshed)extra.push('Refreshed '+place.refreshed);if(place.flags?.length)extra.push('Flags: '+String(place.flags));if(place.sources?.length)extra.push('Sources: '+place.sources.join(', '));detail.append(text('div',extra.join(' · '),'result-data'));item.append(detail);const pick=()=>{selected[source]=place.id;map.panTo([place.lat,place.lon]);let marker=markerLookup[source].get(place.id);if(!marker){marker=addMarker(source,place,index);}marker.openPopup();item.parentNode.querySelectorAll('.result').forEach(n=>n.classList.remove('selected'));item.classList.add('selected');};item.onclick=pick;item.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick();}};list.append(item);});panel.append(list);
const rate=text('div','','rate');rate.append(text('p','Does this list include the destination you expected?'));const buttons=text('div','','rate-buttons');for(const [value,label]of [['correct','✓ Correct'],['partial','~ Close'],['missing','× Missing']]){const b=text('button',label,ratings[source]===value?'active':'');b.disabled=result?.status!=='ok';b.setAttribute('aria-pressed',String(ratings[source]===value));b.onclick=()=>{ratings[source]=value;renderProviders();updateSave();};buttons.append(b);}rate.append(buttons);panel.append(rate);host.append(panel);}}
function renderMarkers(source){layers[source].clearLayers();markerLookup[source].clear();let count=0;for(const [index,p]of(results[source]?.places||[]).entries()){if(!matches(p)||count>=15)continue;count++;addMarker(source,p,index);}}
function addMarker(source,p,index){const icon=L.divIcon({className:'',html:`<div class="number-marker" style="background:${SOURCES[source].color};width:25px;height:25px">${index+1}</div>`,iconSize:[25,25],iconAnchor:[12,12]});const body=text('div','');body.append(text('strong',p.name),text('div',SOURCES[source].name+' · '+Math.round(p.distance)+' m'));const marker=L.marker([p.lat,p.lon],{icon}).bindPopup(body).addTo(layers[source]);markerLookup[source].set(p.id,marker);return marker;}
function updateSave(){$('save').disabled=busy||!current||!Object.values(results).some(r=>r.status==='ok')||Object.entries(results).some(([s,r])=>r.status==='ok'&&!ratings[s]);}
$('compare').onclick=async()=>{if(busy)return;const p=fields();if(!$('lat').value||!$('lon').value||!Object.values(p).every(Number.isFinite)||Math.abs(p.lat)>80||Math.abs(p.lon)>179.9){$('global-status').textContent='Enter valid coordinates first.';return;}invalidate();const id=runId;$('filter').value='';busy=true;current={...p};$('compare').disabled=true;$('global-status').textContent='Comparing real data. Each source appears as it finishes…';Object.keys(SOURCES).forEach(s=>results[s]={status:'loading'});renderProviders();await Promise.all(Object.keys(SOURCES).map(async source=>{try{const data=await api('query/'+source,p);if(id!==runId)return;results[source]=data;renderMarkers(source);}catch(err){if(id!==runId)return;results[source]={status:'error',message:err.message};}if(id===runId)renderProviders();}));if(id!==runId)return;busy=false;$('compare').disabled=false;$('global-status').textContent='Comparison finished. Rate each available source below.';updateSave();};
$('save').onclick=()=>{if($('save').disabled)return;const title=$('expected').value.trim();if(!title){$('expected').focus();$('global-status').textContent='Name the expected destination before saving your ratings.';return;}const report={id:crypto.randomUUID(),date:new Date().toISOString(),label:title,radius:current.radius,ratings:{...ratings},sources:Object.fromEntries(Object.keys(SOURCES).map(s=>[s,{status:results[s]?.status,release:results[s]?.release,total:results[s]?.total,selectedRank:(results[s]?.places||[]).findIndex(p=>p.id===selected[s])+1||null}]))};cases.push(report);try{localStorage.setItem('jd-places-lab-cases',JSON.stringify(cases));}catch{cases.pop();$('global-status').textContent='Browser storage is unavailable. Enable local storage and try again.';return;}$('save').disabled=true;current=null;$('global-status').textContent='Comparison saved locally. Choose another destination to keep testing.';renderScores();};
function renderScores(){$('case-count').textContent=cases.length;const host=$('score-summary');host.replaceChildren();for(const [s,c]of Object.entries(SOURCES)){const rated=cases.filter(r=>r.ratings?.[s]);const correct=rated.filter(r=>r.ratings[s]==='correct').length;const box=text('div','','summary-box');box.append(text('span',c.name),text('strong',rated.length?Math.round(correct/rated.length*100)+'%':'—'),text('p',`${correct} correct / ${rated.length} rated · unavailable runs excluded`));host.append(box);}$('saved-cases').replaceChildren();if(!cases.length)$('saved-cases').append(text('p','Your saved comparisons will appear here.','hint'));for(const c of cases.slice().reverse()){const row=text('div','','saved-case');row.append(text('strong',c.label),text('p',Object.keys(SOURCES).map(s=>SOURCES[s].name+': '+(c.ratings?.[s]||'not rated')).join(' · ')));$('saved-cases').append(row);}}
$('scores-toggle').onclick=()=>{$('scorecard').hidden=!$('scorecard').hidden;if(!$('scorecard').hidden)$('scorecard').scrollIntoView({behavior:'smooth'});};
$('clear').onclick=()=>{if(!confirm('Clear all saved comparison ratings in this browser?'))return;cases=[];localStorage.removeItem('jd-places-lab-cases');renderScores();};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({tool:'JourneyDeck Places Lab',note:'Manual public-destination ratings. No coordinates, tokens, or source records included.',cases},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='journeydeck-place-ratings.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('connect').onclick=()=>{$('connect-status').textContent='';$('connection').showModal();};$('close-connection').onclick=()=>{$('token').value='';$('connection').close();};$('connection').addEventListener('close',()=>{$('token').value='';});
$('connection-form').onsubmit=async e=>{e.preventDefault();try{await api('connect',{token:$('token').value.trim()});$('token').value='';await status();$('connection').close();invalidate();$('global-status').textContent='Token connected. Compare a public destination to verify dataset access.';}catch(err){$('connect-status').textContent=err.message;}};
$('disconnect').onclick=async()=>{await api('connect',{token:''});await status();$('token').value='';$('connection').close();invalidate();};
function setTheme(light){document.body.classList.toggle('light',light);$('theme').textContent=light?'Dark mode':'Light mode';try{localStorage.setItem('jd-places-lab-theme',light?'light':'dark');}catch{}}
$('theme').onclick=()=>setTheme(!document.body.classList.contains('light'));try{setTheme(localStorage.getItem('jd-places-lab-theme')==='light');}catch{}
status().then(renderProviders).catch(()=>{$('global-status').textContent='Local server unavailable. Restart Places Lab.';});renderProviders();renderScores();
