(function(){
  const $=window.DriveOSDom.byId,escapeHtml=window.DriveOSDom.escapeHtml,setText=window.DriveOSDom.setText;
  function create({state,api,money,refreshRecaps}){
    function render(data){const summary=data.summary30||{};setText('charge30Sessions',summary.sessions??0,'0');setText('charge30Energy',summary.energyAddedKWh??0,'0');setText('charge30Cost',summary.cost==null?'--':money(summary.cost),'--');setText('charge30Superchargers',summary.superchargerSessions??0,'0');const rate=data.settings?.electricityRateCents,input=$('electricityRateInput');if(input&&document.activeElement!==input)input.value=rate==null?'':rate;const container=$('chargingHistory');if(!container)return;const sessions=state.chargingSessions||[];if(!sessions.length){container.innerHTML='<div class="empty-state"><h3>No charging sessions yet</h3><p>Tessie charging history will appear here.</p></div>';return;}container.innerHTML=sessions.slice(0,30).map(session=>`<article class="charge-session-card"><div class="charge-session-main"><div><strong>${escapeHtml(session.location||'Unknown location')}</strong><span>${escapeHtml(session.dateLabel)} · ${escapeHtml(session.startTime)} → ${escapeHtml(session.endTime)}</span></div><span class="charge-kind ${session.isSupercharger?'supercharger':''}">${session.isSupercharger?'Supercharger':'Charging'}</span></div><div class="charge-session-metrics"><div><span>Energy</span><strong>${session.energyAddedKWh??'--'} kWh</strong></div><div><span>Battery</span><strong>${session.startingBattery??'--'}% → ${session.endingBattery??'--'}%</strong></div><div><span>Miles added</span><strong>${session.milesAdded??'--'} mi</strong></div><div><span>Cost</span><strong>${session.displayCost==null?'--':money(session.displayCost)}</strong><small>${session.costType==='estimated'?'estimated':session.costType==='recorded'?'recorded':''}</small></div></div></article>`).join('');}
    async function load(){try{const data=await api.get('/api/charging');state.chargingSessions=data.sessions||[];render(data);}catch(error){const container=$('chargingHistory');if(container)container.innerHTML=`<div class="empty-state"><p>${escapeHtml(error.message)}</p></div>`;}}
    async function saveRate(){const input=$('electricityRateInput'),button=$('saveElectricityRate');if(!input||!button)return;button.disabled=true;try{const raw=input.value.trim();await api.post('/api/charging/settings',{electricityRateCents:raw===''?null:Number(raw)});await Promise.allSettled([load(),refreshRecaps()]);}finally{button.disabled=false;}}
    return Object.freeze({load,render,saveRate});
  }
  window.DriveOSFeatures=window.DriveOSFeatures||{};window.DriveOSFeatures.charging=Object.freeze({create});
})();
