(function(){
  function create({state,api,applyFilter}){
    const $=id=>document.getElementById(id),MAX_BYTES=1572864;
    const escape=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
    const drivesFor=collection=>new Set(collection.driveIds||[]);
    const formatBytes=value=>value>=1048576?`${(value/1048576).toFixed(1)} MB`:`${Math.max(1,Math.round(value/1024))} KB`;
    function close(){const modal=$("journeyCollectionModal");if(!modal)return;modal.classList.remove("open");modal.setAttribute("aria-hidden","true");}
    function updateCount(){const count=$("journeyCollectionDriveList")?.querySelectorAll("input:checked").length||0;$("journeyCollectionSelectionCount").textContent=`${count} selected`;}
    function driveChoice(drive,selected){return `<label class="journey-collection-drive-choice"><input type="checkbox" value="${escape(drive.id)}" ${selected.has(drive.id)?"checked":""}><span><strong>${escape(drive.shortDateLabel||drive.dateLabel||"Drive")}</strong><small>${escape(drive.startingLocation||"Start")} &rarr; ${escape(drive.endingLocation||"Destination")} &middot; ${escape(drive.miles??0)} mi</small></span></label>`;}
    function renderAttachments(items=[]){const list=$("journeyAttachmentList");if(!list)return;list.innerHTML=items.length?items.map(item=>`<article class="journey-attachment-item"><div><strong title="${escape(item.fileName)}">${escape(item.fileName)}</strong><small>${escape(formatBytes(item.byteLength))}</small></div><span class="journey-attachment-item-actions"><button class="text-button" type="button" data-open-attachment="${escape(item.id)}">Open</button><button class="text-button" type="button" data-remove-attachment="${escape(item.id)}">Remove</button></span></article>`).join(""):'<div class="journey-attachment-empty">No photos or files yet.</div>';list.querySelectorAll("[data-open-attachment]").forEach(button=>button.addEventListener("click",()=>openAttachment(button.dataset.openAttachment)));list.querySelectorAll("[data-remove-attachment]").forEach(button=>button.addEventListener("click",()=>removeAttachment(button.dataset.removeAttachment)));}
    async function loadAttachments(collectionId){$("journeyAttachmentMessage").textContent="";try{const data=await api.post("/api/collections/attachments/list",{collectionId});renderAttachments(data.attachments||[]);}catch(error){$("journeyAttachmentMessage").textContent=error.message;}}
    function open(collection=null){const modal=$("journeyCollectionModal");if(!modal)return;const selected=drivesFor(collection||{});$("journeyCollectionId").value=collection?.id||"";$("journeyCollectionName").value=collection?.name||"";$("journeyCollectionDescription").value=collection?.description||"";$("journeyCollectionModalHeading").textContent=collection?"Edit collection":"New collection";$("deleteJourneyCollection").hidden=!collection;$("journeyCollectionMessage").textContent="";$("journeyAttachmentSection").hidden=!collection;renderAttachments([]);if(collection)void loadAttachments(collection.id);$("journeyCollectionDriveList").innerHTML=state.drives.slice(0,100).map(drive=>driveChoice(drive,selected)).join("")||'<p class="muted">No drives are available yet.</p>';$("journeyCollectionDriveList").querySelectorAll("input").forEach(input=>input.addEventListener("change",updateCount));updateCount();modal.classList.add("open");modal.setAttribute("aria-hidden","false");$("journeyCollectionName").focus();}
    function render(){const container=$("journeyCollections"),status=$("journeyCollectionsStatus");if(!container)return;status.textContent=state.collections.length?`${state.collections.length} collection${state.collections.length===1?"":"s"}`:"No collections yet";container.innerHTML=state.collections.length?state.collections.map(collection=>{const ids=drivesFor(collection),members=state.drives.filter(drive=>ids.has(drive.id));const latest=members[0]?.shortDateLabel||"No drives yet";return `<article class="journey-collection-card"><div><strong>${escape(collection.name)}</strong><p>${escape(collection.description||"A saved group of journeys")}</p><span>${ids.size} drive${ids.size===1?"":"s"} &middot; Latest ${escape(latest)}</span></div><div class="journey-collection-card-actions"><button class="secondary-button" type="button" data-view-collection="${escape(collection.id)}" ${ids.size?"":"disabled"}>View drives</button><button class="text-button" type="button" data-edit-collection="${escape(collection.id)}">Manage</button></div></article>`;}).join(""):'<div class="favorite-routes-empty"><strong>Create your first collection</strong><span>Group existing drives without changing the original JourneyDeck history.</span></div>';container.querySelectorAll("[data-view-collection]").forEach(button=>button.addEventListener("click",()=>{const collection=state.collections.find(item=>item.id===button.dataset.viewCollection);if(collection)applyFilter(collection.driveIds,collection.name);}));container.querySelectorAll("[data-edit-collection]").forEach(button=>button.addEventListener("click",()=>open(state.collections.find(item=>item.id===button.dataset.editCollection))));}
    async function load(){try{const data=await api.get("/api/collections");state.collections=Array.isArray(data.collections)?data.collections:[];render();}catch(error){$("journeyCollectionsStatus").textContent=error.message;}}
    async function save(event){event.preventDefault();const submit=event.currentTarget.querySelector('[type="submit"]');submit.disabled=true;$("journeyCollectionMessage").textContent="Saving…";try{const collection=await api.post("/api/collections/save",{id:$("journeyCollectionId").value||null,name:$("journeyCollectionName").value,description:$("journeyCollectionDescription").value,driveIds:Array.from($("journeyCollectionDriveList").querySelectorAll("input:checked"),input=>input.value)});state.collections=[collection,...state.collections.filter(item=>item.id!==collection.id)];render();close();}catch(error){$("journeyCollectionMessage").textContent=error.message;}finally{submit.disabled=false;}}
    async function remove(){const id=$("journeyCollectionId").value;if(!id||!confirm("Delete this collection? Your drives will remain untouched."))return;$("deleteJourneyCollection").disabled=true;try{await api.post("/api/collections/delete",{collectionId:id});state.collections=state.collections.filter(item=>item.id!==id);render();close();}catch(error){$("journeyCollectionMessage").textContent=error.message;}finally{$("deleteJourneyCollection").disabled=false;}}
    const bytesToBase64=bytes=>{let value="";for(let index=0;index<bytes.length;index+=32768)value+=String.fromCharCode(...bytes.subarray(index,index+32768));return btoa(value);};
    async function prepareFile(file){if(!file.type.startsWith("image/")){if(file.size>MAX_BYTES)throw new Error(`${file.name} is larger than 1.5 MB.`);return {fileName:file.name,contentType:file.type,dataBase64:bytesToBase64(new Uint8Array(await file.arrayBuffer()))};}try{const bitmap=await createImageBitmap(file),scale=Math.min(1,1920/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/jpeg",.82));if(!blob||blob.size>MAX_BYTES)throw new Error("Photo could not be reduced below 1.5 MB.");return {fileName:file.name.replace(/\.[^.]+$/,"")+".jpg",contentType:"image/jpeg",dataBase64:bytesToBase64(new Uint8Array(await blob.arrayBuffer()))};}catch(error){if(file.size>MAX_BYTES)throw error;return {fileName:file.name,contentType:file.type,dataBase64:bytesToBase64(new Uint8Array(await file.arrayBuffer()))};}}
    async function addAttachments(event){const files=Array.from(event.target.files||[]),collectionId=$("journeyCollectionId").value,message=$("journeyAttachmentMessage");event.target.value="";if(!collectionId||!files.length)return;message.textContent=`Adding ${files.length} file${files.length===1?"":"s"}…`;try{for(const file of files){const prepared=await prepareFile(file);await api.post("/api/collections/attachments/add",{collectionId,...prepared});}message.textContent="Added.";await loadAttachments(collectionId);}catch(error){message.textContent=error.message;}}
    async function openAttachment(attachmentId){const message=$("journeyAttachmentMessage");try{message.textContent="Opening…";const item=await api.post("/api/collections/attachments/get",{attachmentId}),binary=atob(item.dataBase64),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:item.contentType}));window.open(url,"_blank","noopener");setTimeout(()=>URL.revokeObjectURL(url),60000);message.textContent="";}catch(error){message.textContent=error.message;}}
    async function removeAttachment(attachmentId){if(!confirm("Remove this photo or file from the journey?"))return;const message=$("journeyAttachmentMessage");try{await api.post("/api/collections/attachments/remove",{attachmentId});message.textContent="Removed.";await loadAttachments($("journeyCollectionId").value);}catch(error){message.textContent=error.message;}}
    $("newJourneyCollection")?.addEventListener("click",()=>open());$("journeyCollectionForm")?.addEventListener("submit",save);$("deleteJourneyCollection")?.addEventListener("click",remove);$("journeyAttachmentInput")?.addEventListener("change",addAttachments);document.querySelectorAll("[data-close-collection-modal]").forEach(element=>element.addEventListener("click",close));return Object.freeze({load,render,open,close});
  }
  window.DriveOSFeatures=window.DriveOSFeatures||{};window.DriveOSFeatures.collections=Object.freeze({create});
})();
