(function(){
  function batteryText(drive){return drive.startingBattery==null||drive.endingBattery==null?'--':`${drive.startingBattery}% → ${drive.endingBattery}%`;}
  function compactLocation(value){if(!value)return'Unknown location';const parts=value.split(',').map(p=>p.trim()).filter(Boolean);if(parts.length<=2)return value;return `${parts[0]}, ${parts[1]}`;}
  function driveRouteText(drive){return `${drive.startingLocation||drive.rawStartingLocation||''} → ${drive.endingLocation||drive.rawEndingLocation||''}`.trim();}
  function normalizeDriveCollection(drives){return (Array.isArray(drives)?drives:[]).filter(Boolean).map(drive=>({...drive,soundtrack:Array.isArray(drive.soundtrack)?drive.soundtrack.filter(Boolean):[]}));}
  function visibleDriveCollection(drives,expanded,limit=10){const collection=Array.isArray(drives)?drives:[];return expanded?collection:collection.slice(0,Math.max(0,limit));}
  function driveSearchHaystack(drive){return [drive.id,drive.dateLabel,drive.shortDateLabel,drive.dateIso,drive.dateNumeric,drive.startTime,drive.endTime,drive.startingLocation,drive.endingLocation,drive.rawStartingLocation,drive.rawEndingLocation,drive.tessieTag,drive.driverProfile,drive.miles,drive.durationMinutes,drive.efficiencyWhMi,...(drive.soundtrack||[]).filter(Boolean).flatMap(song=>[song.track,song.artist,song.album])].map(v=>String(v??'').toLocaleLowerCase()).join(' ');}
  const degreesToRadians=value=>value*Math.PI/180;
  function geoDistanceMiles(lat1,lon1,lat2,lon2){const values=[lat1,lon1,lat2,lon2].map(Number);if(!values.every(Number.isFinite))return Number.POSITIVE_INFINITY;const [a,b,c,d]=values,dLat=degreesToRadians(c-a),dLon=degreesToRadians(d-b),h=Math.sin(dLat/2)**2+Math.cos(degreesToRadians(a))*Math.cos(degreesToRadians(c))*Math.sin(dLon/2)**2;return 2*3958.7613*Math.asin(Math.min(1,Math.sqrt(h)));}
  const normalizedLocationText=value=>String(value||'').toLocaleLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  function routeAddressesMatch(a,b){return normalizedLocationText(a)&&normalizedLocationText(a)===normalizedLocationText(b);}
  function driveFitsRouteCluster(drive,cluster){const has=[drive.startingLatitude,drive.startingLongitude,drive.endingLatitude,drive.endingLongitude,cluster.startingLatitude,cluster.startingLongitude,cluster.endingLatitude,cluster.endingLongitude].map(Number).every(Number.isFinite);if(has)return geoDistanceMiles(drive.startingLatitude,drive.startingLongitude,cluster.startingLatitude,cluster.startingLongitude)<=.75&&geoDistanceMiles(drive.endingLatitude,drive.endingLongitude,cluster.endingLatitude,cluster.endingLongitude)<=.75;return routeAddressesMatch(drive.startingLocation,cluster.startingLocation)&&routeAddressesMatch(drive.endingLocation,cluster.endingLocation);}
  function detectFavoriteRoutes(drives){const clusters=[];[...drives].sort((a,b)=>String(b.startedAt).localeCompare(String(a.startedAt))).forEach(drive=>{if(!drive.startingLocation&&!drive.endingLocation)return;let cluster=clusters.find(candidate=>driveFitsRouteCluster(drive,candidate));if(!cluster){cluster={startingLocation:drive.startingLocation||'Unknown start',endingLocation:drive.endingLocation||'Unknown destination',startingLatitude:drive.startingLatitude,startingLongitude:drive.startingLongitude,endingLatitude:drive.endingLatitude,endingLongitude:drive.endingLongitude,drives:[]};clusters.push(cluster);}cluster.drives.push(drive);});return clusters.filter(cluster=>cluster.drives.length>=2).map((cluster,index)=>{const distances=cluster.drives.map(d=>Number(d.miles)).filter(Number.isFinite),durations=cluster.drives.map(d=>Number(d.durationMinutes)).filter(Number.isFinite),efficiencies=cluster.drives.map(d=>Number(d.efficiencyWhMi)).filter(Number.isFinite),average=values=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null;return{id:`route-${index+1}`,startingLocation:cluster.startingLocation,endingLocation:cluster.endingLocation,count:cluster.drives.length,driveIds:cluster.drives.map(d=>d.id),lastDrivenAt:cluster.drives[0]?.startedAt||null,lastDrivenLabel:cluster.drives[0]?.shortDateLabel||'',averageMiles:average(distances),averageMinutes:average(durations),averageWhMi:average(efficiencies)};}).sort((a,b)=>b.count!==a.count?b.count-a.count:String(b.lastDrivenAt).localeCompare(String(a.lastDrivenAt))).slice(0,3);}
  function cityFromLocation(value){const parts=String(value||'').split(',').map(p=>p.trim()).filter(Boolean);return parts.length>1?parts[parts.length-2]:parts[0]||'';}
  function money(value){const number=Number(value);return Number.isFinite(number)?number.toLocaleString(undefined,{style:'currency',currency:'USD'}):'--';}
  function locationDisplay(location,rawLocation){if(!location)return rawLocation||'Unknown location';if(rawLocation&&location!==rawLocation)return `${location} · ${rawLocation}`;return location;}
  window.DriveOSFeatures=window.DriveOSFeatures||{};window.DriveOSFeatures.drives=Object.freeze({batteryText,compactLocation,driveRouteText,normalizeDriveCollection,visibleDriveCollection,driveSearchHaystack,degreesToRadians,geoDistanceMiles,normalizedLocationText,routeAddressesMatch,driveFitsRouteCluster,detectFavoriteRoutes,cityFromLocation,money,locationDisplay});
})();
