(function(){
  const $=id=>document.getElementById(id),decode=value=>Uint8Array.from(atob(value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"=")),c=>c.charCodeAt(0)),encode=value=>btoa(String.fromCharCode(...new Uint8Array(value))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
  async function post(path,body={}){const response=await fetch(path,{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Request failed.");return data;}
  function supported(){return !!(window.PublicKeyCredential&&navigator.credentials&&AuthenticatorAttestationResponse.prototype.getPublicKey);}
  async function refresh(){const status=$("passkeyStatus"),add=$("passkeyRegisterButton"),remove=$("passkeyRemoveButton");if(!status)return;if(!supported()){status.textContent="Passkeys are not supported in this browser.";add.hidden=true;return;}const record=await fetch("/api/auth/passkey/status",{credentials:"same-origin"}).then(r=>r.json()).catch(()=>({registered:false}));status.textContent=record.registered?"Face ID or a device passkey is enabled for owner sign-in.":"Add a passkey secured by Face ID, Touch ID, or your device lock.";add.textContent=record.registered?"Replace passkey":"Enable Face ID";remove.hidden=!record.registered;}
  async function register(){const button=$("passkeyRegisterButton"),message=$("passkeyMessage");button.disabled=true;message.textContent="";try{const o=await post("/api/auth/passkey/register/options");const credential=await navigator.credentials.create({publicKey:{challenge:decode(o.challenge),rp:{id:o.rpId,name:o.rpName},user:{id:decode(o.userId),name:o.userName,displayName:"JourneyDeck owner"},pubKeyCredParams:[{type:"public-key",alg:-7}],authenticatorSelection:{authenticatorAttachment:"platform",residentKey:"preferred",userVerification:"required"},attestation:"none",timeout:60000}});const publicKey=credential.response.getPublicKey();if(!publicKey)throw new Error("This browser did not return a usable passkey public key.");await post("/api/auth/passkey/register/verify",{challengeId:o.challengeId,credentialId:encode(credential.rawId),clientDataJSON:encode(credential.response.clientDataJSON),authenticatorData:encode(credential.response.getAuthenticatorData()),publicKeySpki:encode(publicKey),transports:credential.response.getTransports?.()||[]});message.textContent="Face ID/passkey sign-in is ready.";await refresh();}catch(error){if(error?.name!=="NotAllowedError")message.textContent=error.message||"Passkey setup failed.";}finally{button.disabled=false;}}
  async function remove(){if(!confirm("Remove Face ID/passkey sign-in? Password sign-in will remain available."))return;const message=$("passkeyMessage");try{await post("/api/auth/passkey/remove");message.textContent="Passkey removed.";await refresh();}catch(error){message.textContent=error.message;}}
  document.addEventListener("DOMContentLoaded",()=>{$("passkeyRegisterButton")?.addEventListener("click",register);$("passkeyRemoveButton")?.addEventListener("click",remove);void refresh();});
})();
