(function(){
  const {$,escapeHtml}= { $:window.DriveOSDom.byId,escapeHtml:window.DriveOSDom.escapeHtml };
  function create({state,api,compactLocation,refresh}){
    async function save(location,label){await api.post('/api/places/alias',{location,label});await refresh();}
    function render(){const container=$('placeNamesList');const status=$('placeNamesStatus');if(!container)return;const places=state.placeCandidates||[];if(status)status.textContent=`${places.length} repeated locations`;if(!places.length){container.innerHTML='<div class="empty-state"><p>No repeated Tessie locations are available yet.</p></div>';return;}container.innerHTML=places.slice(0,18).map((place,index)=>`<div class="place-name-row"><div class="place-name-copy"><strong>${escapeHtml(place.label||compactLocation(place.location)||'Location')}</strong><span>${escapeHtml(place.location)}</span><small>${place.uses} drive endpoint${place.uses===1?'':'s'}</small></div><div class="place-name-edit"><input data-place-label="${index}" type="text" maxlength="64" value="${escapeHtml(place.label||'')}" placeholder="Name this place" aria-label="Friendly name for ${escapeHtml(place.location)}"><button class="secondary-button" data-place-save="${index}" type="button">${place.label?'Update':'Save'}</button>${place.label?`<button class="text-button" data-place-remove="${index}" type="button">Remove</button>`:''}</div></div>`).join('');container.querySelectorAll('[data-place-save]').forEach(button=>button.addEventListener('click',async()=>{const index=Number(button.dataset.placeSave);const place=places[index];const input=container.querySelector(`[data-place-label="${index}"]`);if(!place||!input)return;button.disabled=true;try{await save(place.location,input.value.trim());}catch(error){if(status)status.textContent=error.message;}finally{button.disabled=false;}}));container.querySelectorAll('[data-place-remove]').forEach(button=>button.addEventListener('click',async()=>{const place=places[Number(button.dataset.placeRemove)];if(place)await save(place.location,'');}));}
    async function load(){try{const data=await api.get('/api/places');state.placeCandidates=data.places||[];render();}catch(error){const status=$('placeNamesStatus');if(status)status.textContent=error.message;}}
    return Object.freeze({load,render,save});
  }
  window.DriveOSFeatures=window.DriveOSFeatures||{};window.DriveOSFeatures.places=Object.freeze({create});
})();
