(function(){
  const $=window.DriveOSDom.byId,escapeHtml=window.DriveOSDom.escapeHtml;
  function create({state,api,money}){
    function render(){const container=$('monthlyRecap'),select=$('recapMonthSelect');if(!container||!select)return;const recap=state.recaps.find(item=>item.monthKey===select.value)||state.recaps[0];if(!recap){container.innerHTML='<div class="empty-state"><p>No monthly recap data yet.</p></div>';return;}const route=recap.favoriteRoute?recap.favoriteRoute.replace(' -> ',' → '):'Not enough drives';container.innerHTML=`<div class="recap-hero"><div><span>${escapeHtml(recap.monthLabel)}</span><strong>${recap.miles??0} miles</strong><small>${recap.driveCount} drive${recap.driveCount===1?'':'s'}</small></div><div class="recap-efficiency"><span>Average efficiency</span><strong>${recap.averageWhMi??'--'}<small> Wh/mi</small></strong></div></div><div class="recap-grid"><article><span>Drive energy</span><strong>${recap.driveEnergyKWh??0}<small> kWh</small></strong></article><article><span>Charging</span><strong>${recap.chargingEnergyKWh??0}<small> kWh</small></strong><small>${recap.chargingSessions} sessions</small></article><article><span>Charging cost</span><strong>${recap.chargingCost==null?'--':money(recap.chargingCost)}</strong><small>${recap.chargingKnownCostSessions} costed sessions</small></article><article><span>Soundtrack plays</span><strong>${recap.soundtrackPlays??0}</strong><small>${recap.uniqueSongs??0} unique songs</small></article><article class="recap-wide"><span>Favorite route</span><strong>${escapeHtml(route)}</strong><small>${recap.favoriteRouteCount||0} trips</small></article><article><span>Longest drive</span><strong>${recap.longestDriveMiles==null?'--':`${recap.longestDriveMiles} mi`}</strong><small>${escapeHtml(recap.longestDriveDate||'')}</small></article><article><span>Top track</span><strong>${escapeHtml(recap.topTrack||'--')}</strong><small>${escapeHtml(recap.topTrackArtist||'')}${recap.topTrackPlays?` · ${recap.topTrackPlays} plays`:''}</small></article><article><span>Top artist</span><strong>${escapeHtml(recap.topArtist||'--')}</strong><small>${recap.topArtistPlays||0} drive plays</small></article></div>`;}
    async function load(){try{const data=await api.get('/api/recap');state.recaps=data.recaps||[];const select=$('recapMonthSelect');if(select){const current=select.value;select.innerHTML=state.recaps.map(item=>`<option value="${escapeHtml(item.monthKey)}">${escapeHtml(item.monthLabel)}</option>`).join('');if(current&&state.recaps.some(item=>item.monthKey===current))select.value=current;select.onchange=render;}render();}catch(error){const container=$('monthlyRecap');if(container)container.innerHTML=`<div class="empty-state"><p>${escapeHtml(error.message)}</p></div>`;}}
    return Object.freeze({load,render});
  }
  window.DriveOSFeatures=window.DriveOSFeatures||{};window.DriveOSFeatures.recaps=Object.freeze({create});
})();
