param([string]$NodePath=$env:DRIVEOS_NODE)
$ErrorActionPreference='Stop';$Root=Split-Path -Parent $PSScriptRoot
$index=Get-Content (Join-Path $Root 'web\index.html') -Raw
$scripts=@([regex]::Matches($index,'<script[^>]+src="(/[^"?]+\.js)')|ForEach-Object{$_.Groups[1].Value})
foreach($src in $scripts){$file=Join-Path (Join-Path $Root 'web') $src.TrimStart('/').Replace('/','\');if(-not(Test-Path -LiteralPath $file)){throw "Missing frontend module: $src"}}
$required=@('/core/build.js','/core/dom.js','/core/state.js','/core/platform.js','/core/api.js','/components/song-artwork.js','/features/navigation.js','/features/pwa.js','/features/theme.js','/features/ignition.js','/features/places.js','/features/charging.js','/features/recaps.js','/features/refresh.js','/features/drives.js','/features/replay.js','/features/music.js','/features/share-cards.js','/features/command-palette.js','/features/dashboard-customization.js','/features/dashboard-widgets.js','/features/data-health.js','/app.js')
foreach($src in $required){if($scripts -notcontains $src){throw "Required frontend module is not loaded: $src"}}
for($i=1;$i -lt $required.Count;$i++){if([array]::IndexOf($scripts,$required[$i-1]) -ge [array]::IndexOf($scripts,$required[$i])){throw "Frontend module order changed near $($required[$i])."}}
$app=Get-Content (Join-Path $Root 'web\app.js') -Raw
if($app -notmatch 'toLocaleDateString\("en-US"' -or $app -notmatch 'month:\s*"2-digit"' -or $app -notmatch 'year:\s*"numeric"'){throw 'Desktop header date is not using compact MM/DD/YYYY formatting.'}
foreach($legacy in @('function initializePwa','function showView','function applyDriveOSTheme','function runDriveOSIgnition','const state = {')){if($app.Contains($legacy)){throw "Extracted frontend implementation returned to app.js: $legacy"}}
foreach($modalId in @('openPlaceNamesModal','placeNamesModal','placeNamesList')){if($index -notmatch ('id="'+$modalId+'"')){throw "Friendly places modal control is missing: $modalId"}}
if($index -notmatch 'id="openPlaceNamesModal"[\s\S]{0,220}>Name your journey places</button>'){throw 'Friendly places is not exposed as the compact Journey Library action.'}
$DriveListIndex=$index.IndexOf('id="allDrives"');$DriveMoreIndex=$index.IndexOf('id="driveLibraryMore"');$ChargingIndex=$index.IndexOf('id="chargingHeading"')
if($DriveListIndex -lt 0 -or $DriveMoreIndex -le $DriveListIndex -or $ChargingIndex -le $DriveMoreIndex){throw 'Drive list, show-all control, and charging history are not in the required order.'}
foreach($shareId in @('shareCardButton','shareCardModal','shareCardCanvas','shareCardDownload')){if($index -notmatch ('id="'+$shareId+'"')){throw "Share card control is missing: $shareId"}}
foreach($commandId in @('commandPaletteButton','commandPalette','commandPaletteInput','commandPaletteResults')){if($index -notmatch ('id="'+$commandId+'"')){throw "Command palette control is missing: $commandId"}}
foreach($healthId in @('dataHealthNav','mobileDataHealthNav','view-health','dataHealthRefresh','mobileSignOutButton')){if($index -notmatch ('id="'+$healthId+'"')){throw "Data Health or mobile session control is missing: $healthId"}}
if($index -notmatch 'id="hostContextFooter"' -or $app -notmatch 'setText\("hostContextFooter", connectionContextLabel\(\)\)'){throw 'The footer is not decorated for local and hosted environments.'}
foreach($dashboardId in @('dashboardCustomizeButton','dashboardCustomizer','dashboardCustomizerList','dashboardWidgetGrid')){if($index -notmatch ('id="'+$dashboardId+'"')){throw "Dashboard customization control is missing: $dashboardId"}}
foreach($widgetId in @('todayDrivingMiles','dashboardSoundtrack')){if($index -notmatch ('id="'+$widgetId+'"')){throw "Dashboard insight widget is missing: $widgetId"}}
$commandPalette=Get-Content (Join-Path $Root 'web\features\command-palette.js') -Raw
if($commandPalette -notmatch 'event\.ctrlKey' -or $commandPalette -notmatch 'ArrowDown' -or $index -notmatch 'Answers use your saved JourneyDeck records'){throw 'Command palette keyboard or privacy behavior is missing.'}
if($commandPalette -notmatch 'looksLikeQuestion' -or $commandPalette -notmatch 'matches\.concat\(askItem\)' -or $commandPalette -notmatch 'relevance\(a, query\)'){throw 'Direct search matches must stay ahead of assistant answers for short queries.'}
if($commandPalette -notmatch 'Scope: while driving' -or $commandPalette -notmatch 'filters\?\.rangeLabel'){throw 'Assistant answers do not expose their driving-only scope and interpreted date range.'}
$dashboardCustomization=Get-Content (Join-Path $Root 'web\features\dashboard-customization.js') -Raw
foreach($capability in @('localStorage','dashboard-size-compact','pinned','hidden','draggable','dashboard-widget-drag-handle','bindWidgetDropEvents','dashboard-widget-resize-handle','nearestSize','pointerdown','positions','blankDropPosition','dashboardGridDropPreview')){if($dashboardCustomization -notmatch [regex]::Escape($capability)){throw "Dashboard customization capability is missing: $capability"}}
$dashboardWidgets=Get-Content (Join-Path $Root 'web\features\dashboard-widgets.js') -Raw
foreach($capability in @('todaySummary','inferMood','data-dashboard-action','openShareCard','openRecap')){if($dashboardWidgets -notmatch [regex]::Escape($capability)){throw "Dashboard insight widget capability is missing: $capability"}}
if($index -notmatch 'Home privacy is locked on'){throw 'Share-card Home privacy lock is missing.'}
if($index -notmatch '>Share to X<'){throw 'Share-card X action is missing.'}
$shareCards=Get-Content (Join-Path $Root 'web\features\share-cards.js') -Raw
if($shareCards -notmatch 'https://x\.com/intent/tweet'){throw 'Official X Web Intent fallback is missing.'}
if($shareCards -notmatch 'JourneyDeckMapTheme' -or $shareCards -notmatch 'tiles\.openfreemap\.org/styles/dark'){throw 'Share-card dark map overview is missing.'}
if($shareCards -match 'vehicleArtwork|loadVehicleArtwork' -or $shareCards -notmatch 'journeydeck-share-card-preferences-v1' -or $shareCards -notmatch 'localStorage\.setItem\(preferenceKey' -or $shareCards -notmatch 'queuePreviewUpdate\(true\)' -or $shareCards -notmatch 'drawRoute\(ctx, card, \{ x: 54, y: 440, w: 972, h: 455 \}, false\)' -or $shareCards -notmatch '"line-color": theme\.routeGlow \|\| theme\.accent'){throw 'Share-card customization must persist and the cinematic hero must remain a theme-aware route map.'}
if($index -notmatch 'data-close-place-modal'){throw 'Friendly places modal backdrop/close control is missing.'}
foreach($searchId in @('driveSearchInput','driveAdvancedToggle','driveAdvancedFilters')){if($index -notmatch ('id="'+$searchId+'"')){throw "Drive search control is missing: $searchId"}}
if($index -notmatch 'id="driveAdvancedFilters"[^>]*hidden'){throw 'Advanced drive filters must be collapsed initially.'}
if($index -notmatch 'placeholder="Enter a city or state'){throw 'The primary drive search is not labeled for city/state search.'}
$styles=Get-Content (Join-Path $Root 'web\styles.css') -Raw
$betaThemeV2=Get-Content (Join-Path $Root 'web\beta-theme-v2.css') -Raw
$referenceDashboard=Get-Content (Join-Path $Root 'web\reference-dashboard.css') -Raw
if($betaThemeV2 -notmatch '(?s)\.topbar \.nav-mobile-icon svg\s*\{[^}]*fill:none;[^}]*stroke:currentColor;'){throw 'Desktop sidebar SVG icons must inherit the purple navigation color.'}
if($referenceDashboard -notmatch '(?s)\.ref-desktop-route > strong\s*\{[^}]*grid-template-columns:minmax\(0,1fr\) auto minmax\(0,1fr\)' -or $referenceDashboard -notmatch '(?s)\.ref-desktop-route > strong b\s*\{[^}]*overflow-wrap:anywhere;[^}]*white-space:normal;'){throw 'Newest journey locations must wrap without truncation.'}
foreach($liveDesktopId in @('liveDriveCharging','liveDriveChargeLimit','liveDriveInsideTemp','liveDriveOutsideTemp','liveDriveFeedStatus','liveDriveOdometer')){if($index -notmatch ('id="'+$liveDesktopId+'"')){throw "Desktop Live Journey detail is missing: $liveDesktopId"}}
if($betaThemeV2 -notmatch '(?s):root\[data-theme\] \.drive-search-box\s*\{[^}]*rgba\(151,61,255,\.34\)[^}]*rgba\(255,83,76,\.13\)' -or $betaThemeV2 -notmatch '(?s)\.live-drive-telemetry\s*\{[^}]*repeat\(4,minmax\(0,1fr\)\)'){throw 'Cinematic search styling or the expanded desktop Live telemetry grid is missing.'}
if($betaThemeV2 -notmatch '(?s):root\[data-theme\] \.detail-metrics > div\s*\{[^}]*rgba\(151,61,255,\.16\)[^}]*linear-gradient\(145deg' -or $betaThemeV2 -notmatch '(?s):root\[data-theme\] \.music-location-form\s*\{[^}]*grid-template-columns:minmax\(280px,1fr\) 112px auto' -or $betaThemeV2 -notmatch '(?s):root\[data-theme\] \.music-location-search\s*\{[^}]*rgba\(151,61,255,\.34\)[^}]*rgba\(255,83,76,\.13\)'){throw 'Journey metrics or music-by-location controls have lost their cinematic styling.'}
if($betaThemeV2 -notmatch '(?s):root\[data-theme\] \.view-drive-button\s*\{[^}]*linear-gradient\(135deg,#ff534c,#ff8a4e\)' -or $betaThemeV2 -notmatch '(?s):root\[data-theme\] \.charging-summary-grid > article,[^{]*\{[^}]*linear-gradient\(145deg' -or $betaThemeV2 -notmatch '(?s):root\[data-theme\] \.replay-vehicle-state > div\s*\{[^}]*rgba\(151,61,255,\.24\)' -or $betaThemeV2 -notmatch '(?s)\.command-palette \.command-palette-search kbd,[^{]*\{[^}]*rgba\(255,126,72,\.42\)'){throw 'Journey actions, charging data, replay telemetry, or command keys have lost their Cinematic theme.'}
if($betaThemeV2 -notmatch '(?s)#newJourneyCollection,[^{]*#openPlaceNamesModal,[^{]*\.view-drive-button\s*\{[^}]*font-size:\.875rem !important'){throw 'Journey Library orange action buttons must share one midpoint text size.'}
if($app -notmatch '(?s)const clock = new Date\(clamped\)\.toLocaleTimeString\(\[\], \{\s*hour: "2-digit",\s*minute: "2-digit",\s*hour12: true' -or $index -notmatch 'id="replayClock" class="replay-telemetry-value">--:--</strong>'){throw 'Journey replay time must use HH:MM AM/PM without seconds.'}
if($index -notmatch '<span>TESLA</span><span>MODEL 3</span><em>Eloise</em>' -or $index -notmatch 'class="ref-hero-road" src="/assets/journeydeck-dashboard-road-hero-v1\.png(?:\?v=[0-9.]+)?"' -or $index -match 'ref-hero-map|ref-map-streets|ref-route-art|ref-hero-car'){throw 'The dashboard hero must use the approved orange-road composition without the former purple map or route overlays.'}
$heroRoadAsset=Join-Path $Root 'web\assets\journeydeck-dashboard-road-hero-v1.png';if(-not(Test-Path -LiteralPath $heroRoadAsset)){throw 'The approved dashboard road hero asset is missing.'}
if($app -notmatch 'tracks\.slice\(1, 21\)' -or $app -notmatch 'v3-recent-scroll' -or $app -notmatch 'v3-recent-columns' -or $styles -notmatch 'dashboard-size-wide\.spotify-panel \.v3-recent-columns'){throw 'Scrollable 20-track Spotify history is missing.'}
if($styles -notmatch '(?s)\.dashboard-size-compact\.spotify-panel \.v3-now-playing\s*\{[^}]*grid-template-columns:\s*112px' -or $styles -notmatch '(?s)\.dashboard-size-compact\.spotify-panel \.v3-recent-list\s*\{[^}]*display:\s*none'){throw 'Compact Spotify Now Playing layout is missing.'}
if($styles -notmatch 'grid-auto-flow:\s*row dense' -or $styles -notmatch 'align-items:\s*stretch' -or $styles -notmatch '(?s)\.dashboard-size-wide\s*\{[^}]*grid-column:\s*1\s*/\s*-1'){throw 'Dashboard size geometry is not standardized.'}
if($styles -notmatch '(?s)\.topbar-right \.theme-switcher\s*\{[^}]*display:\s*inline-flex\s*!important'){throw 'The theme switcher is not restored in the mobile header.'}
if($styles -notmatch 'JourneyDeck 5\.2\.6 - owner mobile bottom navigation' -or $styles -notmatch '@media \(max-width: 1120px\)' -or $styles -notmatch '(?s)\.main-nav\.mobile-nav-portal,\s*body > \.main-nav\s*\{[^}]*border-radius:\s*0\s*!important[^}]*background:\s*rgba\(249,252,253,\.82\)' -or $styles -notmatch '(?s)\.nav-button\.active::after\s*,[^}]*top:\s*0\s*!important'){throw 'Owner phone/tablet navigation is not using the Wife Mode-style bottom bar.'}
$platform=Get-Content (Join-Path $Root 'web\core\platform.js') -Raw
$navigation=Get-Content (Join-Path $Root 'web\features\navigation.js') -Raw
if($platform -notmatch 'isLocalPreview=\(\)=>isLocalHost\(\)\|\|isTailnetRemote\(\)' -or $platform -notmatch 'classList\.toggle\("local-host",isLocalPreview\(\)\)' -or $styles -notmatch 'Local/Tailnet preview mobile navigation concept 7' -or $styles -notmatch 'grid-template-columns:repeat\(5,minmax\(0,1fr\)\)' -or $styles -notmatch '(?s):root\.local-host body\.reference-dashboard-active \.app-shell\s*\{[^}]*padding-bottom:' -or $styles -notmatch '(?s):root\.local-host \.main-nav\.mobile-nav-portal \.nav-button\.active\s*,[^}]*border-color:rgba\(255,113,56,\.78\)[^}]*box-shadow:0 0 10px rgba\(255,91,45,\.75\)' -or $styles -notmatch '(?s):root\.local-host \.main-nav\.mobile-nav-portal \.nav-button\.nav-secondary\s*,[^}]*display:none !important' -or $styles -notmatch '(?s)\.nav-button\.nav-secondary\[data-view="graph"\][^{]*\{[^}]*display:grid !important' -or $index -notmatch 'data-view="graph"[^>]*>.*?<svg viewBox="0 0 24 24"' -or $navigation -notmatch "localPreview\?\['timeline','music','statistics','health'\]:\['graph','timeline','music','statistics','health'\]"){throw 'Local/Tailnet preview mobile navigation does not provide the five-item dashboard-safe concept 7 bar with an orange active glow.'}
if($styles -notmatch '(?s):root\[data-theme="light"\] \.mobile-more-sheet\s*\{[^}]*background:\s*rgba\(249,252,253,\.94\)' -or $styles -notmatch '(?s):root\[data-theme="light"\] \.mobile-more-grid button\s*\{[^}]*color:\s*var\(--text\)'){throw 'The mobile More sheet does not follow the light theme.'}
if($styles -notmatch '(?s)@media \(min-width: 1121px\).*?:root\[data-theme="dark"\] \.main-nav \.nav-button\s*\{[^}]*color:\s*#a9c5cf\s*!important' -or $styles -notmatch '(?s):root\[data-theme="dark"\] \.command-palette-trigger,.*?color:\s*#9fbac4\s*!important'){throw 'Dark desktop header labels do not have sufficient contrast.'}
if($styles -notmatch '(?s):root\[data-theme="dark"\] \.vehicle-charge-summary \.battery-number\s*\{[^}]*color:\s*#eefbff'){throw 'Dark-mode battery percentage contrast is missing.'}
if($styles -notmatch '100dvh - 215px' -or $styles -notmatch 'command-mobile-note' -or $styles -notmatch 'safe-area-inset-top'){throw 'The command palette mobile layout is missing.'}
foreach($mobilePolish in @('data-mobile-label','dashboard-drive-card \{ grid-template-columns: minmax\(0,1fr\) minmax\(0,1fr\) 38px','charging-rate-editor \{ display: grid','background-activity-monitor\.idle \{ display: none','data-theme="light"\] \.live-drive-shell','data-theme="light"\] \.live-drive-overlay')){if(($index + $styles) -notmatch $mobilePolish){throw "Mobile JourneyDeck polish is missing: $mobilePolish"}}
$webBuild = (Get-Content (Join-Path $root 'version.json') -Raw | ConvertFrom-Json).webBuild
if($index -notmatch "rel=`"shortcut icon`"[^>]+journeydeck-cinematic-192\.png\?v=$([regex]::Escape($webBuild))" -or $index -notmatch "apple-touch-icon[^>]+journeydeck-cinematic-180\.png\?v=$([regex]::Escape($webBuild))"){throw 'Safari favicon and home-screen icon declarations are stale.'}
if($styles -notmatch '(?s)\.dashboard-size-wide\.vehicle-panel \.vehicle-car-art\.vehicle-car-model3\.vehicle-car-photo\s*\{[^}]*width:\s*100%\s*!important[^}]*height:\s*100%\s*!important[^}]*object-fit:\s*contain' -or $styles -notmatch 'vehicle-hero-visual::before'){throw 'Wide dashboard vehicle artwork framing is missing.'}
if($index -notmatch 'id="vehicleLocationMap"' -or $app -notmatch 'renderVehicleLocation' -or $styles -notmatch '(?s)\.dashboard-size-wide\.vehicle-panel \.vehicle-dashboard-main\s*\{[^}]*grid-template-columns:'){throw 'Wide vehicle live-location panel is missing.'}
$desktopHost=Get-Content (Join-Path $Root 'desktop\Program.cs') -Raw;$ignition=Get-Content (Join-Path $Root 'web\features\ignition.js') -Raw
if($desktopHost -match 'runDriveOSIgnition' -and $ignition -notmatch 'window\.runDriveOSIgnition\s*=\s*run'){throw 'Desktop ignition compatibility shim is missing.'}
$serviceWorker=Get-Content (Join-Path $Root 'web\service-worker.js') -Raw;if($serviceWorker -notmatch 'pathname\.endsWith\("\.js"\)'){throw 'Service worker no longer treats feature modules as network-only.'}
if(-not $NodePath){$node=Get-Command node.exe -ErrorAction SilentlyContinue;if($node){$NodePath=$node.Source}}
if($NodePath){
    & $NodePath (Join-Path $PSScriptRoot 'frontend-modules.test.js');if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}
    & $NodePath (Join-Path $PSScriptRoot 'startup-refresh.test.js');if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}
}else{Write-Warning 'Node.js unavailable; runtime module tests skipped.'}
Write-Host 'Phase 3 module and load-order tests passed.'
