$ErrorActionPreference='Stop';$Root=Split-Path -Parent $PSScriptRoot
Import-Module (Join-Path $Root 'src\Application\DriveOS.SpotifyExtendedImport.psm1') -Force
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
$Start=[DateTimeOffset]::Parse('2025-06-10T12:00:00-05:00');$Drive=[pscustomobject]@{started_at=$Start.ToUnixTimeSeconds();ended_at=$Start.AddMinutes(30).ToUnixTimeSeconds()}
function New-Entry([string]$Name,[int]$StartMinute,[int]$PlayedMs=180000,[string]$Id='track1'){$PlayedStart=$Start.AddMinutes($StartMinute);[pscustomobject]@{ts=$PlayedStart.AddMilliseconds($PlayedMs).ToUniversalTime().ToString('o');ms_played=$PlayedMs;spotify_track_uri="spotify:track:$Id";master_metadata_track_name=$Name;master_metadata_album_artist_name='Artist';master_metadata_album_album_name='Album'}}
$Entry=New-Entry 'Direct' 5;$Record=ConvertTo-DriveOSSpotifyExtendedRecord $Entry;Assert-True ([DateTimeOffset]::Parse($Record.played_at)-eq$Start.AddMinutes(5).ToUniversalTime()) 'Spotify end time was not converted to playback start.'
$EmojiEntry=New-Entry "Direct$([char]0xD83D)$([char]0xDE80)" 6 180000 'emoji';$EmojiRecord=ConvertTo-DriveOSSpotifyExtendedRecord $EmojiEntry;Assert-True ($EmojiRecord.track-eq'Direct') 'Supplementary Unicode was not made safe for Turso JSON.'
$Plan=New-DriveOSSpotifyExtendedImportPlan -Entries @($Entry,(New-Entry 'Short' 10 10000 'short')) -Drives @($Drive) -RangeFromUtc $Start.AddDays(-1) -RangeToUtc $Start.AddDays(1);Assert-True ($Plan.matchedPlays-eq1-and$Plan.shortPlays-eq1) 'Short-play filtering or direct matching failed.';Assert-True ($Plan.soundtrackRecords[0].songCount-eq@($Plan.soundtrackRecords[0].songs).Count) 'songCount does not match soundtrack length.'
$ExistingYouTube=[pscustomobject]@{id='youtube_music|one';source='youtube_music';track='Direct';artist='Artist';played_at=$Start.AddMinutes(6).ToString('o')};$ExistingSoundtrack=[pscustomobject]@{driveId="$($Drive.started_at)-$($Drive.ended_at)";songs=@([pscustomobject]@{track='Direct';artist='Artist';playedAt=$Start.AddMinutes(6).ToString('o');source='youtube_music';durationMs=0})}
$Authoritative=New-DriveOSSpotifyExtendedImportPlan -Entries @($Entry) -Drives @($Drive) -ExistingHistory @($ExistingYouTube) -ExistingSoundtracks @($ExistingSoundtrack) -RangeFromUtc $Start.AddDays(-1) -RangeToUtc $Start.AddDays(1);Assert-True ($Authoritative.crossProviderMatches-eq1) 'Spotify did not identify the alternate-provider listen.';Assert-True ($Authoritative.soundtrackRecords[0].songs[0].source-eq'spotify'-and$Authoritative.soundtrackRecords[0].songCount-eq1) 'Spotify did not replace the alternate-provider soundtrack projection.'
$Rerun=New-DriveOSSpotifyExtendedImportPlan -Entries @($Entry) -Drives @($Drive) -ExistingHistory @($Record) -ExistingSoundtracks @($Plan.soundtrackRecords[0]) -RangeFromUtc $Start.AddDays(-1) -RangeToUtc $Start.AddDays(1);Assert-True ($Rerun.newHistoryRecords-eq0-and$Rerun.matchedPlays-eq1-and$Rerun.soundtrackRecords[0].songCount-eq1) 'Spotify import is not safely rerunnable.'
$Rounded=$Record.PSObject.Copy();$Rounded.id='rounded-existing';$Rounded.played_at=$Start.AddMinutes(5).AddSeconds(2).ToString('o');$RoundedPlan=New-DriveOSSpotifyExtendedImportPlan -Entries @($Entry) -Drives @($Drive) -ExistingHistory @($Rounded) -RangeFromUtc $Start.AddDays(-1) -RangeToUtc $Start.AddDays(1);Assert-True ($RoundedPlan.newHistoryRecords-eq0-and$RoundedPlan.exactDuplicates-eq1) 'Rounded existing Spotify timestamp was duplicated.'
$Overlap=[pscustomobject]@{started_at=$Start.AddMinutes(4).ToUnixTimeSeconds();ended_at=$Start.AddMinutes(15).ToUnixTimeSeconds()};$Ambiguous=New-DriveOSSpotifyExtendedImportPlan -Entries @($Entry) -Drives @($Drive,$Overlap) -RangeFromUtc $Start.AddDays(-1) -RangeToUtc $Start.AddDays(1);Assert-True ($Ambiguous.ambiguousMatches-eq1-and$Ambiguous.matchedPlays-eq0) 'Ambiguous drive overlap was imported.'
Write-Host 'JourneyDeck Spotify extended-history import checks passed.' -ForegroundColor Green
