$ErrorActionPreference='Stop';$Root=Split-Path -Parent $PSScriptRoot
Import-Module (Join-Path $Root 'src\Application\DriveOS.YouTubeMusicImport.psm1') -Force
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function New-Block([string]$Product,[string]$Id,[string]$Title,[string]$Artist,[string]$Date){return "<div class=`"outer-cell mdl-cell`"><p class=`"mdl-typography--title`">$Product<br></p><div>Watched&nbsp;<a href=`"https://music.youtube.com/watch?v=$Id`">$Title</a><br><a href=`"https://youtube.com/channel/x`">$Artist - Topic</a><br>$Date<br></div></div>"}
$Html='<body>'+ (New-Block 'YouTube Music' 'one' 'Direct' 'Artist' 'Jun 10, 2025, 12:05:00 PM CDT') + (New-Block 'YouTube Music' 'two' 'Boundary' 'Artist' 'Jun 10, 2025, 12:32:00 PM CDT') + (New-Block 'YouTube' 'three' 'Not music product' 'Channel' 'Jun 10, 2025, 12:06:00 PM CDT') + '</body>'
$Records=@(ConvertFrom-DriveOSYouTubeMusicTakeoutHtml $Html);Assert-True ($Records.Count-eq2) 'Only explicit YouTube Music events should be parsed.';Assert-True ($Records[0].artist-eq'Artist') 'Topic suffix was not normalized.'
$Start=[DateTimeOffset]::Parse('2025-06-10T12:00:00-05:00');$Drive=[pscustomobject]@{started_at=$Start.ToUnixTimeSeconds();ended_at=$Start.AddMinutes(30).ToUnixTimeSeconds()}
$Plan=New-DriveOSYouTubeMusicImportPlan -Records $Records -Drives @($Drive) -RangeFromUtc $Start.AddDays(-1) -RangeToUtc $Start.AddDays(1)
Assert-True ($Plan.directMatches-eq1-and$Plan.boundaryReviewMatches-eq1) 'Direct and boundary match buckets are wrong.';Assert-True ($Plan.matchedPlays-eq1) 'Boundary matches must be excluded by default.';Assert-True ($Plan.soundtrackRecords[0].songCount-eq@($Plan.soundtrackRecords[0].songs).Count) 'songCount does not match soundtrack length.'
$WithBoundary=New-DriveOSYouTubeMusicImportPlan -Records $Records -Drives @($Drive) -RangeFromUtc $Start.AddDays(-1) -RangeToUtc $Start.AddDays(1) -IncludeBoundaryMatches;Assert-True ($WithBoundary.matchedPlays-eq2) 'Explicit boundary opt-in did not work.'
$Duplicate=New-DriveOSYouTubeMusicImportPlan -Records @($Records[0]) -Drives @($Drive) -ExistingHistory @([pscustomobject]@{id='spotify';source='spotify';track='Direct';artist='Artist';played_at=$Start.AddMinutes(6).ToString('o')}) -RangeFromUtc $Start.AddDays(-1) -RangeToUtc $Start.AddDays(1);Assert-True ($Duplicate.existingDuplicates-eq1-and$Duplicate.matchedPlays-eq0) 'Existing Spotify play was duplicated.'
$Rerun=New-DriveOSYouTubeMusicImportPlan -Records @($Records[0]) -Drives @($Drive) -ExistingHistory @($Records[0]) -ExistingSoundtracks @($Plan.soundtrackRecords[0]) -RangeFromUtc $Start.AddDays(-1) -RangeToUtc $Start.AddDays(1);Assert-True ($Rerun.alreadyImported-eq1-and$Rerun.newHistoryRecords-eq0-and$Rerun.matchedPlays-eq1) 'A resumed import cannot repair an existing history row.';Assert-True ($Rerun.soundtrackRecords[0].songCount-eq1) 'A resumed projection duplicated an existing soundtrack song.'
$Repeat=$Records[0].PSObject.Copy();$Repeat.id='youtube_music|repeat';$Repeat.played_at=$Start.AddMinutes(6).ToUniversalTime().ToString('o');$Repeat.youtube_video_id='repeat';$Repeat.youtube_url='https://music.youtube.com/watch?v=repeat';$RepeatPlan=New-DriveOSYouTubeMusicImportPlan -Records @($Records[0],$Repeat) -Drives @($Drive) -ExistingHistory @($Records[0],$Repeat) -RangeFromUtc $Start.AddDays(-1) -RangeToUtc $Start.AddDays(1);Assert-True ($RepeatPlan.alreadyImported-eq2-and$RepeatPlan.matchedPlays-eq2-and$RepeatPlan.soundtrackRecords[0].songCount-eq2) 'Same-source repeat listens were collapsed.'
$Overlap=[pscustomobject]@{started_at=$Start.AddMinutes(4).ToUnixTimeSeconds();ended_at=$Start.AddMinutes(15).ToUnixTimeSeconds()};$Ambiguous=New-DriveOSYouTubeMusicImportPlan -Records @($Records[0]) -Drives @($Drive,$Overlap) -RangeFromUtc $Start.AddDays(-1) -RangeToUtc $Start.AddDays(1);Assert-True ($Ambiguous.ambiguousMatches-eq1-and$Ambiguous.matchedPlays-eq0) 'Ambiguous drive match was imported.'
Write-Host 'JourneyDeck YouTube Music import checks passed.' -ForegroundColor Green
