(() => {
  const $ = (id) => document.getElementById(id);
  const escape = (value) => String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[c]);
  const request = async (url, options = {}) => { const response = await fetch(url, { credentials:"same-origin", ...options, headers:{ "Content-Type":"application/json", ...(options.headers || {}) } }); if (!response.ok) throw new Error("Could not load JourneyDeck."); return response.json(); };
  const renderTrips = (target, drives, limit) => { $(target).innerHTML = drives.slice(0, limit).map((drive) => `<article class="trip"><strong>${escape(drive.shortDateLabel || drive.dateLabel)}</strong><span class="trip-route">${escape(drive.startingLocation || "Start")} → ${escape(drive.endingLocation || "Destination")}</span><span class="trip-meta">${escape(drive.miles ?? 0)} mi · ${escape(drive.durationMinutes ?? 0)} min</span></article>`).join("") || '<article class="trip"><strong>No recent trips yet</strong><span class="trip-meta">Trips will appear here after a drive.</span></article>'; };
  const activate = (id) => { document.querySelectorAll(".view").forEach((view) => view.classList.toggle("active", view.id === id)); document.querySelectorAll(".bottom-nav button").forEach((button) => button.classList.toggle("active", button.dataset.view === id)); window.scrollTo({top:0, behavior:"smooth"}); };
  document.querySelectorAll("[data-view]").forEach((button) => button.addEventListener("click", () => activate(button.dataset.view)));
  $("themeToggle").addEventListener("click", () => { const dark = document.documentElement.dataset.theme !== "dark"; document.documentElement.dataset.theme = dark ? "dark" : "light"; localStorage.setItem("journeydeck-wife-theme", document.documentElement.dataset.theme); });
  document.documentElement.dataset.theme = localStorage.getItem("journeydeck-wife-theme") || "light";
  $("openFull").addEventListener("click", async () => { try { $("openFull").disabled = true; await request("/api/wife/mode", {method:"POST", body:JSON.stringify({mode:"full"})}); location.replace("/"); } catch { $("openFull").disabled = false; } });
  Promise.all([request("/api/auth/session"), request("/api/wife/summary"), request("/api/wife/live")]).then(([, summary, live]) => { $("wifeVehicleName").textContent = summary.vehicle.name || "Your car"; $("wifeBattery").textContent = `${summary.vehicle.battery ?? "—"}%`; $("wifeRange").textContent = summary.vehicle.rangeMiles == null ? "— mi" : `${Math.round(summary.vehicle.rangeMiles)} mi`; $("wifeTodayMiles").textContent = summary.today.miles ?? 0; $("wifeTodayTrips").textContent = summary.today.trips ?? 0; $("wifeUpdated").textContent = summary.vehicle.gpsAsOf ? `Updated ${summary.vehicle.gpsAsOf}` : "Car status is up to date"; renderTrips("wifeRecentHome", summary.drives, 3); renderTrips("wifeTrips", summary.drives, 20); if (live.latitude != null && live.longitude != null) { $("mapDot").hidden = false; $("wifeLocationText").textContent = `${Number(live.latitude).toFixed(4)}, ${Number(live.longitude).toFixed(4)}`; } else { $("wifeLocationText").textContent = "Location is not available right now"; } }).catch(() => { $("wifeUpdated").textContent = "JourneyDeck could not refresh right now"; });
})();
